USE QLYBANHANGNOITHAT

CREATE ROLE NHANVIEN;
CREATE ROLE KHACH;

GRANT SELECT, INSERT, UPDATE ON THANH_TOAN_TIEN TO NHANVIEN;
GRANT SELECT ON THANH_TOAN_TIEN TO KHACH;

CREATE TRIGGER authorizations_Chekout
ON THANH_TOAN_TIEN
FOR INSERT, UPDATE, DELETE
AS
DECLARE @roleEmployee TINYINT;
DECLARE @roleCustomer TINYINT;
SELECT @roleEmployee = role FROM NHANVIEN;
SELECT @roleCustomer = role FROM KHACH;
IF (@roleCustomer = 0  AND NOT IS_MEMBER('KHACH') = 1)
BEGIN
    RAISERROR('You do not have permission to perform this action.', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END
ELSE IF (@roleEmployee = 1 AND NOT IS_MEMBER('NHANVIEN') = 1)
BEGIN
    RAISERROR('Success.', 16, 1);
    ROLLBACK TRANSACTION;
    RETURN;
END

